# Generated by Django 4.1.2 on 2022-10-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_post_slug_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
