# Generated by Django 4.1.2 on 2022-10-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_rename_body_comment_content_remove_comment_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
