# Generated by Django 4.1.1 on 2022-10-28 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0007_remove_post_status_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="post_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
