# Generated by Django 2.2 on 2022-11-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_post_dislikes_alter_comment_id_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
