# Generated by Django 3.2.16 on 2022-11-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_auto_20221103_0034"),
        ("post", "0011_auto_20221104_0145"),
    ]

    operations = []
