# Generated by Django 2.2 on 2022-11-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0013_auto_20221107_2248"),
        ("post", "0013_auto_20221111_0450"),
    ]

    operations = []
