# Generated by Django 2.2 on 2022-12-15 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0015_auto_20221114_0315"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="beginner_react",
            field=models.ManyToManyField(
                related_name="beg_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="expert_react",
            field=models.ManyToManyField(
                related_name="exp_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="legend_react",
            field=models.ManyToManyField(
                related_name="leg_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="medium_react",
            field=models.ManyToManyField(
                related_name="med_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
