# Generated by Django 3.2.16 on 2022-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=10, null=True)),
                ('img', models.CharField(blank=True, max_length=4000, null=True)),
                ('url', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
