# Generated by Django 2.2 on 2022-11-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20221107_2248'),
        ('news', '0003_auto_20221111_0450'),
    ]

    operations = [
    ]
